name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install pnpm & init deps
      run: |
        npm i -g pnpm
        pnpm i
    - name: Run Test
      run: |
        pnpm test
        echo test, and deploy your project.
